// <auto-generated />
using System;
using BusinessObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessObjects.Migrations
{
    [DbContext(typeof(DiamondStoreContext))]
    [Migration("20240615100951_UpdateModels")]
    partial class UpdateModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObjects.TblAccount", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AccountId")
                        .HasName("PK__Tbl_Acco__349DA58609E534F8");

                    b.HasIndex(new[] { "Username" }, "UQ__Tbl_Acco__536C85E41BFA36AF")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Tbl_Account", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblCustomer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime");

                    b.Property<double?>("DiscountRate")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Ranking")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("CustomerId")
                        .HasName("PK__Tbl_Cust__A4AE64B8C76863DC");

                    b.HasIndex(new[] { "AccountId" }, "UQ__Tbl_Cust__349DA58770E38A22")
                        .IsUnique()
                        .HasFilter("[AccountID] IS NOT NULL");

                    b.ToTable("Tbl_Customer", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblDiamondGradingReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReportID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("GemId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("GemID");

                    b.Property<DateTime?>("GenerateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ReportId")
                        .HasName("PK__Tbl_Diam__D5BD48E52E336E34");

                    b.HasIndex(new[] { "GemId" }, "UQ__Tbl_Diam__F101D5A1ADE3DE48")
                        .IsUnique()
                        .HasFilter("[GemID] IS NOT NULL");

                    b.ToTable("Tbl_DiamondGradingReport", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblGem", b =>
                {
                    b.Property<string>("GemId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("GemID");

                    b.Property<double?>("CaratWeight")
                        .HasColumnType("float");

                    b.Property<string>("Clarity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cut")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fluorescence")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GemName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Origin")
                        .HasColumnType("bit");

                    b.Property<string>("Polish")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Shape")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Symmetry")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GemId")
                        .HasName("PK__Tbl_Gem__F101D5A015C1ADDA");

                    b.ToTable("Tbl_Gem", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblGemPriceList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("CaratWeight")
                        .HasColumnType("float");

                    b.Property<string>("Clarity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cut")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EffDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("Origin")
                        .HasColumnType("bit");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<double?>("Size")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__Tbl_GemP__3214EC27348C24BE");

                    b.ToTable("Tbl_GemPriceList", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblMaterialCategory", b =>
                {
                    b.Property<string>("MaterialId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("MaterialID");

                    b.Property<string>("MaterialName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaterialId")
                        .HasName("PK__Tbl_Mate__C50613170572B2E9");

                    b.ToTable("Tbl_MaterialCategory", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblMaterialPriceList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EffDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MaterialId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("MaterialID");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__Tbl_Mate__3214EC2733CA32F6");

                    b.HasIndex(new[] { "MaterialId" }, "UQ__Tbl_Mate__C50613165F43B652")
                        .IsUnique()
                        .HasFilter("[MaterialID] IS NOT NULL");

                    b.ToTable("Tbl_MaterialPriceList", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblMembership", b =>
                {
                    b.Property<double?>("DiscountRate")
                        .HasColumnType("float");

                    b.Property<double?>("MaxSpend")
                        .HasColumnType("float");

                    b.Property<double?>("MinSpend")
                        .HasColumnType("float");

                    b.Property<string>("Ranking")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("Tbl_Membership", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<string>("OrderStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ReceiveDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ShipStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShipperId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("ShipperID");

                    b.Property<DateTime?>("ShippingDate")
                        .HasColumnType("datetime");

                    b.Property<string>("StaffId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("StaffID");

                    b.HasKey("OrderId")
                        .HasName("PK__Tbl_Orde__C3905BAFC20CF98E");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ShipperId");

                    b.HasIndex("StaffId");

                    b.ToTable("Tbl_Order", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblOrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<double?>("CustomizedAmount")
                        .HasColumnType("float");

                    b.Property<int?>("CustomizedSize")
                        .HasColumnType("int");

                    b.Property<double?>("FinalPrice")
                        .HasColumnType("float");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<string>("ProductId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("ProductID");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<double?>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("OrderDetailId")
                        .HasName("PK__Tbl_Orde__D3B9D30CBFB0BB31");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("Tbl_OrderDetail", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<double?>("Deposits")
                        .HasColumnType("float");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<string>("PayDetail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Tbl_Paym__3214EC27C0CCA6F0");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.ToTable("Tbl_Payment", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblProduct", b =>
                {
                    b.Property<string>("ProductId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("ProductID");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("CategoryID");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("GemCost")
                        .HasColumnType("float");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("MaterialCost")
                        .HasColumnType("float");

                    b.Property<double?>("PriceRate")
                        .HasColumnType("float");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ProductSize")
                        .HasColumnType("int");

                    b.Property<double?>("ProductionCost")
                        .HasColumnType("float");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<double?>("UnitSizePrice")
                        .HasColumnType("float");

                    b.HasKey("ProductId")
                        .HasName("PK__Tbl_Prod__B40CC6ED155971E4");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tbl_Product", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblProductCategory", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("CategoryID");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Tbl_Prod__19093A2B32299BF5");

                    b.ToTable("Tbl_ProductCategory", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblProductGem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GemId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("GemID");

                    b.Property<string>("ProductId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("ProductID");

                    b.HasKey("Id")
                        .HasName("PK__Tbl_Prod__3214EC27942C9E1C");

                    b.HasIndex(new[] { "ProductId" }, "UQ__Tbl_Prod__B40CC6EC1F7E9BD5")
                        .IsUnique()
                        .HasFilter("[ProductID] IS NOT NULL");

                    b.HasIndex(new[] { "GemId" }, "UQ__Tbl_Prod__F101D5A1A6E8002C")
                        .IsUnique()
                        .HasFilter("[GemID] IS NOT NULL");

                    b.ToTable("Tbl_ProductGem", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblProductMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaterialId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("MaterialID");

                    b.Property<string>("ProductId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("ProductID");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__Tbl_Prod__3214EC277BCBCBB9");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProductId");

                    b.ToTable("Tbl_ProductMaterial", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblSaleStaff", b =>
                {
                    b.Property<string>("StaffId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("StaffID");

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StaffId")
                        .HasName("PK__Tbl_Sale__96D4AAF7DEF1C585");

                    b.HasIndex(new[] { "AccountId" }, "UQ__Tbl_Sale__349DA587A9D9823E")
                        .IsUnique()
                        .HasFilter("[AccountID] IS NOT NULL");

                    b.ToTable("Tbl_SaleStaff", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblShipper", b =>
                {
                    b.Property<string>("ShipperId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("ShipperID");

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ShipperId")
                        .HasName("PK__Tbl_Ship__1F8AFFB9884AFCE1");

                    b.HasIndex(new[] { "AccountId" }, "UQ__Tbl_Ship__349DA587C27466AD")
                        .IsUnique()
                        .HasFilter("[AccountID] IS NOT NULL");

                    b.ToTable("Tbl_Shipper", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblWarranty", b =>
                {
                    b.Property<int>("WarrantyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WarrantyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarrantyId"));

                    b.Property<int?>("OrderDetailId")
                        .HasColumnType("int")
                        .HasColumnName("OrderDetailID");

                    b.Property<DateTime?>("WarrantyEndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("WarrantyStartDate")
                        .HasColumnType("datetime");

                    b.HasKey("WarrantyId")
                        .HasName("PK__Tbl_Warr__2ED318F348B52C11");

                    b.HasIndex(new[] { "OrderDetailId" }, "UQ__Tbl_Warr__D3B9D30D6EAA58F2")
                        .IsUnique()
                        .HasFilter("[OrderDetailID] IS NOT NULL");

                    b.ToTable("Tbl_Warranty", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblCustomer", b =>
                {
                    b.HasOne("BusinessObjects.TblAccount", "Account")
                        .WithOne("TblCustomer")
                        .HasForeignKey("BusinessObjects.TblCustomer", "AccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Tbl_Custo__Accou__3B75D760");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObjects.TblDiamondGradingReport", b =>
                {
                    b.HasOne("BusinessObjects.TblGem", "Gem")
                        .WithOne("TblDiamondGradingReport")
                        .HasForeignKey("BusinessObjects.TblDiamondGradingReport", "GemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Tbl_Diamo__GemID__5CD6CB2B");

                    b.Navigation("Gem");
                });

            modelBuilder.Entity("BusinessObjects.TblMaterialPriceList", b =>
                {
                    b.HasOne("BusinessObjects.TblMaterialCategory", "Material")
                        .WithOne("TblMaterialPriceList")
                        .HasForeignKey("BusinessObjects.TblMaterialPriceList", "MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Tbl_Mater__Mater__276EDEB3");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("BusinessObjects.TblOrder", b =>
                {
                    b.HasOne("BusinessObjects.TblCustomer", "Customer")
                        .WithMany("TblOrders")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK__Tbl_Order__Custo__4BAC3F29");

                    b.HasOne("BusinessObjects.TblShipper", "Shipper")
                        .WithMany("TblOrders")
                        .HasForeignKey("ShipperId")
                        .HasConstraintName("FK__Tbl_Order__Shipp__4D94879B");

                    b.HasOne("BusinessObjects.TblSaleStaff", "Staff")
                        .WithMany("TblOrders")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK__Tbl_Order__Staff__4CA06362");

                    b.Navigation("Customer");

                    b.Navigation("Shipper");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("BusinessObjects.TblOrderDetail", b =>
                {
                    b.HasOne("BusinessObjects.TblOrder", "Order")
                        .WithMany("TblOrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Tbl_Order__Order__5070F446");

                    b.HasOne("BusinessObjects.TblProduct", "Product")
                        .WithMany("TblOrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Tbl_Order__Produ__5165187F");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BusinessObjects.TblPayment", b =>
                {
                    b.HasOne("BusinessObjects.TblCustomer", "Customer")
                        .WithMany("TblPayments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Tbl_Payme__Custo__5535A963");

                    b.HasOne("BusinessObjects.TblOrder", "Order")
                        .WithMany("TblPayments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Tbl_Payme__Order__5441852A");

                    b.Navigation("Customer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BusinessObjects.TblProduct", b =>
                {
                    b.HasOne("BusinessObjects.TblProductCategory", "Category")
                        .WithMany("TblProducts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Tbl_Produ__Categ__3F466844");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BusinessObjects.TblProductGem", b =>
                {
                    b.HasOne("BusinessObjects.TblGem", "Gem")
                        .WithOne("TblProductGem")
                        .HasForeignKey("BusinessObjects.TblProductGem", "GemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Tbl_Produ__GemID__48CFD27E");

                    b.HasOne("BusinessObjects.TblProduct", "Product")
                        .WithOne("TblProductGem")
                        .HasForeignKey("BusinessObjects.TblProductGem", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Tbl_Produ__Produ__47DBAE45");

                    b.Navigation("Gem");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BusinessObjects.TblProductMaterial", b =>
                {
                    b.HasOne("BusinessObjects.TblMaterialCategory", "Material")
                        .WithMany("TblProductMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Tbl_Produ__Mater__4316F928");

                    b.HasOne("BusinessObjects.TblProduct", "Product")
                        .WithMany("TblProductMaterials")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Tbl_Produ__Produ__4222D4EF");

                    b.Navigation("Material");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BusinessObjects.TblSaleStaff", b =>
                {
                    b.HasOne("BusinessObjects.TblAccount", "Account")
                        .WithOne("TblSaleStaff")
                        .HasForeignKey("BusinessObjects.TblSaleStaff", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Tbl_SaleS__Accou__33D4B598");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObjects.TblShipper", b =>
                {
                    b.HasOne("BusinessObjects.TblAccount", "Account")
                        .WithOne("TblShipper")
                        .HasForeignKey("BusinessObjects.TblShipper", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Tbl_Shipp__Accou__37A5467C");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObjects.TblWarranty", b =>
                {
                    b.HasOne("BusinessObjects.TblOrderDetail", "OrderDetail")
                        .WithOne("TblWarranty")
                        .HasForeignKey("BusinessObjects.TblWarranty", "OrderDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Tbl_Warra__Order__59063A47");

                    b.Navigation("OrderDetail");
                });

            modelBuilder.Entity("BusinessObjects.TblAccount", b =>
                {
                    b.Navigation("TblCustomer");

                    b.Navigation("TblSaleStaff");

                    b.Navigation("TblShipper");
                });

            modelBuilder.Entity("BusinessObjects.TblCustomer", b =>
                {
                    b.Navigation("TblOrders");

                    b.Navigation("TblPayments");
                });

            modelBuilder.Entity("BusinessObjects.TblGem", b =>
                {
                    b.Navigation("TblDiamondGradingReport");

                    b.Navigation("TblProductGem");
                });

            modelBuilder.Entity("BusinessObjects.TblMaterialCategory", b =>
                {
                    b.Navigation("TblMaterialPriceList");

                    b.Navigation("TblProductMaterials");
                });

            modelBuilder.Entity("BusinessObjects.TblOrder", b =>
                {
                    b.Navigation("TblOrderDetails");

                    b.Navigation("TblPayments");
                });

            modelBuilder.Entity("BusinessObjects.TblOrderDetail", b =>
                {
                    b.Navigation("TblWarranty");
                });

            modelBuilder.Entity("BusinessObjects.TblProduct", b =>
                {
                    b.Navigation("TblOrderDetails");

                    b.Navigation("TblProductGem");

                    b.Navigation("TblProductMaterials");
                });

            modelBuilder.Entity("BusinessObjects.TblProductCategory", b =>
                {
                    b.Navigation("TblProducts");
                });

            modelBuilder.Entity("BusinessObjects.TblSaleStaff", b =>
                {
                    b.Navigation("TblOrders");
                });

            modelBuilder.Entity("BusinessObjects.TblShipper", b =>
                {
                    b.Navigation("TblOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
