// <auto-generated />
using System;
using BusinessObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessObjects.Migrations
{
    [DbContext(typeof(DiamondStoreContext))]
    partial class DiamondStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObjects.TblAccount", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("AccountID");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AccountId")
                        .HasName("PK__Tbl_Acco__349DA5867ADF35A8");

                    b.HasIndex(new[] { "Username" }, "UQ__Tbl_Acco__536C85E44347055E")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Tbl_Account", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblCustomer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("CustomerID");

                    b.Property<string>("AccountId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("AccountID");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime");

                    b.Property<double?>("DiscountRate")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Ranking")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("CustomerId")
                        .HasName("PK__Tbl_Cust__A4AE64B8C8CB26DA");

                    b.HasIndex("AccountId");

                    b.ToTable("Tbl_Customer", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblDiamondGradingReport", b =>
                {
                    b.Property<string>("ReportId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("ReportID");

                    b.Property<string>("GemId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("GemID");

                    b.Property<DateTime?>("GenerateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ReportId")
                        .HasName("PK__Tbl_Diam__D5BD48E5ACF3216E");

                    b.HasIndex(new[] { "GemId" }, "UQ__Tbl_Diam__F101D5A15BF1F2BE")
                        .IsUnique()
                        .HasFilter("[GemID] IS NOT NULL");

                    b.ToTable("Tbl_DiamondGradingReport", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblGem", b =>
                {
                    b.Property<string>("GemId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("GemID");

                    b.Property<double?>("CaratWeight")
                        .HasColumnType("float");

                    b.Property<string>("Clarity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cut")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fluorescence")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GemName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Origin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Polish")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Shape")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Symmetry")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GemId")
                        .HasName("PK__Tbl_Gem__F101D5A0CC383096");

                    b.ToTable("Tbl_Gem", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblGemPriceList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("CaratWeight")
                        .HasColumnType("float");

                    b.Property<string>("Clarity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cut")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EffDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Origin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<double?>("Size")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__Tbl_GemP__3214EC2708DD23BE");

                    b.ToTable("Tbl_GemPriceList", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblMaterialCategory", b =>
                {
                    b.Property<string>("MaterialId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("MaterialID");

                    b.Property<string>("MaterialName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaterialId")
                        .HasName("PK__Tbl_Mate__C50613171622D165");

                    b.ToTable("Tbl_MaterialCategory", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblMaterialPriceList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EffDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MaterialId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("MaterialID");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__Tbl_Mate__3214EC27B4831432");

                    b.HasIndex(new[] { "MaterialId" }, "UQ__Tbl_Mate__C50613168298B295")
                        .IsUnique()
                        .HasFilter("[MaterialID] IS NOT NULL");

                    b.ToTable("Tbl_MaterialPriceList", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblMembership", b =>
                {
                    b.Property<double?>("DiscountRate")
                        .HasColumnType("float");

                    b.Property<double?>("MaxSpend")
                        .HasColumnType("float");

                    b.Property<double?>("MinSpend")
                        .HasColumnType("float");

                    b.Property<string>("Ranking")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("Tbl_Membership", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblOrder", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("OrderID");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("CustomerID");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<string>("OrderStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ReceiveDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ShipperId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("ShipperID");

                    b.Property<DateTime?>("ShippingDate")
                        .HasColumnType("datetime");

                    b.Property<string>("StaffId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("StaffID");

                    b.HasKey("OrderId")
                        .HasName("PK__Tbl_Orde__C3905BAFA3C9AEB3");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StaffId");

                    b.ToTable("Tbl_Order", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblOrderDetail", b =>
                {
                    b.Property<string>("OrderDetailId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("OrderDetailID");

                    b.Property<double?>("CustomizedAmount")
                        .HasColumnType("float");

                    b.Property<int?>("CustomizedSize")
                        .HasColumnType("int");

                    b.Property<double?>("FinalPrice")
                        .HasColumnType("float");

                    b.Property<string>("OrderId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("OrderID");

                    b.Property<string>("ProductId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("ProductID");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<double?>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("OrderDetailId")
                        .HasName("PK__Tbl_Orde__D3B9D30C0DEBB22D");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("Tbl_OrderDetail", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblPayment", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("CustomerID");

                    b.Property<double?>("Deposits")
                        .HasColumnType("float");

                    b.Property<string>("OrderId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("OrderID");

                    b.Property<string>("PayDetail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.ToTable("Tbl_Payment", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblProduct", b =>
                {
                    b.Property<string>("ProductId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("ProductID");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("CategoryID");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("GemCost")
                        .HasColumnType("float");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("MaterialCost")
                        .HasColumnType("float");

                    b.Property<double?>("PriceRate")
                        .HasColumnType("float");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ProductSize")
                        .HasColumnType("int");

                    b.Property<double?>("ProductionCost")
                        .HasColumnType("float");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ProductId")
                        .HasName("PK__Tbl_Prod__B40CC6EDC2BE8400");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tbl_Product", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblProductCategory", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("CategoryID");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Tbl_Prod__19093A2B0200BE5A");

                    b.ToTable("Tbl_ProductCategory", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblProductMaterial", b =>
                {
                    b.Property<string>("ProductId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("ProductID");

                    b.Property<string>("MaterialId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("MaterialID");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("ProductId", "MaterialId")
                        .HasName("PK__Tbl_Prod__D85CA7DC593BB93E");

                    b.HasIndex("MaterialId");

                    b.ToTable("Tbl_ProductMaterial", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblStaff", b =>
                {
                    b.Property<string>("StaffId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("StaffID");

                    b.Property<string>("AccountId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("AccountID");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StaffId")
                        .HasName("PK__Tbl_Staf__96D4AAF7001894A6");

                    b.HasIndex(new[] { "AccountId" }, "UQ__Tbl_Staf__349DA5876E727721")
                        .IsUnique()
                        .HasFilter("[AccountID] IS NOT NULL");

                    b.ToTable("Tbl_Staff", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblWarranty", b =>
                {
                    b.Property<string>("WarrantyId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("WarrantyID");

                    b.Property<string>("OrderDetailId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("OrderDetailID");

                    b.Property<DateTime?>("WarrantyEndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("WarrantyStartDate")
                        .HasColumnType("datetime");

                    b.HasKey("WarrantyId")
                        .HasName("PK__Tbl_Warr__2ED318F3294E9FAC");

                    b.HasIndex(new[] { "OrderDetailId" }, "UQ__Tbl_Warr__D3B9D30DC4EE2FAF")
                        .IsUnique()
                        .HasFilter("[OrderDetailID] IS NOT NULL");

                    b.ToTable("Tbl_Warranty", (string)null);
                });

            modelBuilder.Entity("TblProductGem", b =>
                {
                    b.Property<string>("ProductId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("ProductID");

                    b.Property<string>("GemId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("GemID");

                    b.HasKey("ProductId", "GemId")
                        .HasName("PK__Tbl_Prod__AB1CDBB7E43079B5");

                    b.HasIndex("GemId");

                    b.ToTable("Tbl_ProductGem", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TblCustomer", b =>
                {
                    b.HasOne("BusinessObjects.TblAccount", "Account")
                        .WithMany("TblCustomers")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Tbl_Custo__Accou__36B12243");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObjects.TblDiamondGradingReport", b =>
                {
                    b.HasOne("BusinessObjects.TblGem", "Gem")
                        .WithOne("TblDiamondGradingReport")
                        .HasForeignKey("BusinessObjects.TblDiamondGradingReport", "GemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Tbl_Diamo__GemID__5441852A");

                    b.Navigation("Gem");
                });

            modelBuilder.Entity("BusinessObjects.TblMaterialPriceList", b =>
                {
                    b.HasOne("BusinessObjects.TblMaterialCategory", "Material")
                        .WithOne("TblMaterialPriceList")
                        .HasForeignKey("BusinessObjects.TblMaterialPriceList", "MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Tbl_Mater__Mater__276EDEB3");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("BusinessObjects.TblOrder", b =>
                {
                    b.HasOne("BusinessObjects.TblCustomer", "Customer")
                        .WithMany("TblOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Tbl_Order__Custo__44FF419A");

                    b.HasOne("BusinessObjects.TblStaff", "Staff")
                        .WithMany("TblOrders")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Tbl_Order__Staff__45F365D3");

                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("BusinessObjects.TblOrderDetail", b =>
                {
                    b.HasOne("BusinessObjects.TblOrder", "Order")
                        .WithMany("TblOrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Tbl_Order__Order__48CFD27E");

                    b.HasOne("BusinessObjects.TblProduct", "Product")
                        .WithMany("TblOrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Tbl_Order__Produ__49C3F6B7");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BusinessObjects.TblPayment", b =>
                {
                    b.HasOne("BusinessObjects.TblCustomer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Tbl_Payme__Custo__4CA06362");

                    b.HasOne("BusinessObjects.TblOrder", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Tbl_Payme__Order__4BAC3F29");

                    b.Navigation("Customer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BusinessObjects.TblProduct", b =>
                {
                    b.HasOne("BusinessObjects.TblProductCategory", "Category")
                        .WithMany("TblProducts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Tbl_Produ__Categ__3A81B327");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BusinessObjects.TblProductMaterial", b =>
                {
                    b.HasOne("BusinessObjects.TblMaterialCategory", "Material")
                        .WithMany("TblProductMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Tbl_Produ__Mater__3E52440B");

                    b.HasOne("BusinessObjects.TblProduct", "Product")
                        .WithMany("TblProductMaterials")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Tbl_Produ__Produ__3D5E1FD2");

                    b.Navigation("Material");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BusinessObjects.TblStaff", b =>
                {
                    b.HasOne("BusinessObjects.TblAccount", "Account")
                        .WithOne("TblStaff")
                        .HasForeignKey("BusinessObjects.TblStaff", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Tbl_Staff__Accou__33D4B598");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObjects.TblWarranty", b =>
                {
                    b.HasOne("BusinessObjects.TblOrderDetail", "OrderDetail")
                        .WithOne("TblWarranty")
                        .HasForeignKey("BusinessObjects.TblWarranty", "OrderDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Tbl_Warra__Order__5070F446");

                    b.Navigation("OrderDetail");
                });

            modelBuilder.Entity("TblProductGem", b =>
                {
                    b.HasOne("BusinessObjects.TblGem", null)
                        .WithMany()
                        .HasForeignKey("GemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Tbl_Produ__GemID__4222D4EF");

                    b.HasOne("BusinessObjects.TblProduct", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Tbl_Produ__Produ__412EB0B6");
                });

            modelBuilder.Entity("BusinessObjects.TblAccount", b =>
                {
                    b.Navigation("TblCustomers");

                    b.Navigation("TblStaff");
                });

            modelBuilder.Entity("BusinessObjects.TblCustomer", b =>
                {
                    b.Navigation("TblOrders");
                });

            modelBuilder.Entity("BusinessObjects.TblGem", b =>
                {
                    b.Navigation("TblDiamondGradingReport");
                });

            modelBuilder.Entity("BusinessObjects.TblMaterialCategory", b =>
                {
                    b.Navigation("TblMaterialPriceList");

                    b.Navigation("TblProductMaterials");
                });

            modelBuilder.Entity("BusinessObjects.TblOrder", b =>
                {
                    b.Navigation("TblOrderDetails");
                });

            modelBuilder.Entity("BusinessObjects.TblOrderDetail", b =>
                {
                    b.Navigation("TblWarranty");
                });

            modelBuilder.Entity("BusinessObjects.TblProduct", b =>
                {
                    b.Navigation("TblOrderDetails");

                    b.Navigation("TblProductMaterials");
                });

            modelBuilder.Entity("BusinessObjects.TblProductCategory", b =>
                {
                    b.Navigation("TblProducts");
                });

            modelBuilder.Entity("BusinessObjects.TblStaff", b =>
                {
                    b.Navigation("TblOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
